version: "3.8"

services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80" # Expose Nginx on port 8080
    volumes:
      - ./nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro # Mount the Nginx configuration
    depends_on:
      - todo-frontend
      - todo-backend

  todo-frontend:
    image: todo-frontend:dev
    volumes:
      - ./todo-frontend/src:/usr/src/app/src
      - ./todo-frontend/public:/usr/src/app/public
    environment:
      - NODE_ENV=development
      - VITE_BACKEND_URL=http://localhost:8080/api
    command: npm run dev
    working_dir: /usr/src/app

  todo-backend:
    image: todo-backend:dev
    volumes:
      - ./todo-backend:/usr/src/app
    environment:
      - MONGO_URL=mongodb://root:example@mongo:27017/the_database
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data:/data/db

  redis:
    image: redis
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data:
